# Utiliser une image de base avec Miniconda
FROM continuumio/miniconda3

# Mettre à jour Conda
RUN conda update -n base -c defaults conda -y

# Installer les dépendances système
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libxext6 \
    libsm6 \
    libxrender1 \
    wget

# Créer un utilisateur non-root
RUN useradd -m appuser

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY --chown=appuser:appuser Agent.py launch.py TicTacToeEnv.py utils.py c.pth /app

# Créer l'environnement Conda
RUN conda create -n streamlit_env python=3.11 -y

# Activer l'environnement Conda
SHELL ["conda", "run", "-n", "streamlit_env", "/bin/bash", "-c"]

# Installer les dépendances Python dans l'environnement Conda
RUN conda install streamlit numpy pytorch -y

# Basculer vers l'utilisateur non-root
USER appuser

# Exposer le port sur lequel Streamlit fonctionne
EXPOSE 8501

# Commande pour exécuter l'application Streamlit
CMD ["/bin/bash", "-c", "conda run -n streamlit_env streamlit run --server.address 0.0.0.0 launch.py"]
